###
GET http://localhost:3003/user/91a2529e-4eec-4a76-9339-7ecffe5881f8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5MWEyNTI5ZS00ZWVjLTRhNzYtOTMzOS03ZWNmZmU1ODgxZjgiLCJjb21wYW55SWQiOiIxMTBlMGFjMC02YjVkLTRkMjAtOGZlYi0yZDhhMmEyZjdlNmQiLCJpYXQiOjE3Njk5MTYxMTEsImV4cCI6MTc3MDAwMjUxMX0.muZxPXqmHfIxKNYU8NEC1BqkS3l7orBRL_OZ5jHC0rs