###
PUT http://localhost:3003/user/91a2529e-4eec-4a76-9339-7ecffe5881f8
Content-Type: application/json

{
    
    "id": "91a2529e-4eec-4a76-9339-7ecffe5881f8",
    "name": "Diego Romanio de Almeida",
    "email": "diego@qosit.cloud",
    "password": "Gn@887697"
}
